apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-fund-transfer-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  API_VERSION: "3.0"
  POD_NAME: "go-fund-transfer.k8"
  PORT: "5005"
  DB_HOST: "rds-proxy-db-arch.proxy-couoacqalfwt.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_SCHEMA: "public"
  DB_DRIVER: "postgres"
  SETPOD_AZ: "false"
  ENV: "dev"

  KAFKA_USER: "admin"
  KAFKA_PASSWORD: "admin"
  KAFKA_PROTOCOL: "SASL_SSL"
  KAFKA_MECHANISM: "SCRAM-SHA-512"
  KAFKA_CLIENT_ID: "GO-FUND-TRANSFER"
  KAFKA_BROKER_1: "b-1.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_BROKER_2: "b-2.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_BROKER_3: "b-3.mskarch01.x25pj7.c3.kafka.us-east-2.amazonaws.com:9096"
  KAFKA_PARTITION: "3"
  KAFKA_REPLICATION: "2"
  TOPIC_CREDIT: "topic.credit.01"
  TOPIC_DEBIT: "topic.debit.01"
  TOPIC_TRANSFER: "topic.transfer.01"
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-01-xray-collector.default.svc.cluster.local:4317"

  NAME_SERVICE_01: "go-account"
  URL_SERVICE_01: https://vpce.global.dev.caradhras.io/pv/get"
  METHOD_SERVICE_01: "GET"
  X_APIGW_API_ID_SERVICE_01: "129t4y8eoj"

  NAME_SERVICE_02: "go-debit"
  URL_SERVICE_02: https://vpce.global.dev.caradhras.io/pv/add"
  METHOD_SERVICE_02: "POST"
  X_APIGW_API_ID_SERVICE_02: "cy5ry2263h"

  NAME_SERVICE_03: "go-credit"
  URL_SERVICE_03: "https://vpce.global.dev.caradhras.io/pv/add"
  METHOD_SERVICE_03: "POST
  X_APIGW_API_ID_SERVICE_03: "7egms7zn67"

  #SERVICE_URL_DOMAIN: "http://svc-go-account.test-a.svc.cluster.local:5000"
  #SERVICE_URL_DOMAIN: "https://vpce.global.dev.caradhras.io/pv"
  #QUEUE_URL_CREDIT: "https://sqs.us-east-2.amazonaws.com/908671954593/sqs-credit.fifo"
  #AWS_REGION: "us-east-2"
  #POD_QUEUE_TYPE: "kafka"
  #SERVICE_URL_JWT_SA: "https://go-auth0.architecturedev.caradhras.io"
  #SECRET_JWT_SA_CREDENTIAL: "go-fund-credential-sa"